BASE_DIR = '/Users/ding/Desktop/NUS-proj/'
DATA_DIR = '/Users/ding/Desktop/NUS-proj/dataV2/'

IMG_SIZE = (224, 224)
CLASS_NUM = 5
HIDDEN_LAYER_PERCEPTRONS = [512]
DROPOUT = 0.32
CUSTOM_LAYERS = 2 + 3 * len(HIDDEN_LAYER_PERCEPTRONS) + 1
CHECKPOINT_INDEX = 3
FROZEN_LAYERS = 10
BATCH_SIZE = 32