BASE_DIR = '/Users/ding/Desktop/NUS-proj/'
DATA_DIR = '/Users/ding/Desktop/NUS-proj/mdata_balanced/'

# IMG_SIZE = (240, 320) # H * W
IMG_SIZE = (224, 224) # H * W
CLASS_NUM = 5
HIDDEN_LAYER_PERCEPTRONS = [512]
DROPOUT = 0.35
CUSTOM_LAYERS = 2 + 3 * len(HIDDEN_LAYER_PERCEPTRONS) + 1
CHECKPOINT_INDEX = 9
FROZEN_LAYERS = 10
BATCH_SIZE = 32
# MODEL = 'NASNETMOBILE'
MODEL = 'MOBILENETV2'
# Dataset Balanced